##Program 1/2, Load Files

Refeeding Data Sampling Script To Understand Table Relationships For Doctoral Research Project

Programmer: James Green,
Email: jg1984@shp.rutgers.edu,
Updated: 10/17/2024

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In the ICU files, check the distinct values of ordercategoryname for Glenn.

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/inputevents.csv')

In [ ]:
# Get the distinct values and sort them
distinct_values = sorted(df['ordercategoryname'].unique())

# Print each distinct value on a separate line
for value in distinct_values:
    print(value)

01-Drips
02-Fluids (Crystalloids)
03-IV Fluid Bolus
04-Fluids (Colloids)
05-Med Bolus
06-Insulin (Non IV)
07-Blood Products
08-Antibiotics (IV)
09-Antibiotics (Non IV)
10-Prophylaxis (IV)
11-Prophylaxis (Non IV)
12-Parenteral Nutrition
13-Enteral Nutrition
14-Oral/Gastric Intake
15-Supplements
16-Pre Admission/Non-ICU

## Start the hospital file sample creation.

Lab Sample File - 10,000 rows

Admissions Sample File - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/admissions.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/admiss_samp.csv', index=False)

df.dtypes

subject_id                int64
hadm_id                   int64
admittime                object
dischtime                object
deathtime                object
admission_type           object
admit_provider_id        object
admission_location       object
discharge_location       object
insurance                object
language                 object
marital_status           object
race                     object
edregtime                object
edouttime                object
hospital_expire_flag      int64
Unnamed: 16             float64
dtype: object

drgcodes Sample File - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/drgcodes.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/drgcodes_samp.csv', index=False)

df.dtypes

subject_id         int64
hadm_id            int64
drg_type          object
drg_code           int64
description       object
drg_severity     float64
drg_mortality    float64
dtype: object

diagnosis_icd Sample File - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/diagnoses_icd.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/diagicd_samp.csv', index=False)

df.dtypes

subject_id      int64
hadm_id         int64
seq_num         int64
icd_code       object
icd_version     int64
dtype: object

emar Sample File - 10,000 rows

In [ ]:
import pandas as pd

# Path to the large CSV file
csv_file_path = '/content/drive/MyDrive/Research/Refeeding/hosp/emar.csv'

# Initialize an empty DataFrame to hold the sample
sample_data = []

# Load the CSV file in chunks
chunk_size = 10000  # Number of rows per chunk
for chunk in pd.read_csv(csv_file_path, chunksize=chunk_size):
    # Append the first 10,000 rows from the first chunk
    sample_data.append(chunk)

    # Stop after collecting enough samples
    if len(sample_data) * chunk_size >= 10000:
        break

# Concatenate the list of DataFrames into a single DataFrame
df_sample = pd.concat(sample_data)[:10000]  # Ensure it contains only 10,000 rows

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/emar_samp.csv', index=False)

# Display data types
print(df_sample.dtypes)

subject_id             int64
hadm_id              float64
emar_id               object
emar_seq               int64
poe_id                object
pharmacy_id          float64
enter_provider_id     object
charttime             object
medication            object
event_txt             object
scheduletime          object
storetime             object
dtype: object

hcpcsevents - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/hcpcsevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/hcpcsevents_samp.csv', index=False)

df.dtypes

subject_id            int64
hadm_id               int64
chartdate            object
hcpcs_cd             object
seq_num               int64
short_description    object
dtype: object

microbiologyevents - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/microbiologyevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/microbiologyevents_samp.csv', index=False)

df.dtypes

<ipython-input-5-5470d754e354>:4: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/microbiologyevents.csv')

microevent_id            int64
subject_id               int64
hadm_id                float64
micro_specimen_id        int64
order_provider_id       object
chartdate               object
charttime               object
spec_itemid              int64
spec_type_desc          object
test_seq                 int64
storedate               object
storetime               object
test_itemid              int64
test_name               object
org_itemid             float64
org_name                object
isolate_num            float64
quantity                object
ab_itemid              float64
ab_name                 object
dilution_text           object
dilution_comparison     object
dilution_value         float64
interpretation          object
comments                object
dtype: object

omr 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/omr.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/omr_samp.csv', index=False)

df.dtypes

subject_id       int64
chartdate       object
seq_num          int64
result_name     object
result_value    object
dtype: object

patients - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/patients.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/patients_samp.csv', index=False)

df.dtypes

subject_id            int64
gender               object
anchor_age            int64
anchor_year           int64
anchor_year_group    object
dod                  object
dtype: object

pharmacy - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/pharmacy.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/pharmacy_samp.csv', index=False)

df.dtypes

In [ ]:
df.dtypes

subject_id             int64
hadm_id                int64
pharmacy_id            int64
poe_id                object
starttime             object
stoptime              object
medication            object
proc_type             object
status                object
entertime             object
verifiedtime          object
route                 object
frequency             object
disp_sched            object
infusion_type         object
sliding_scale         object
lockout_interval      object
basal_rate           float64
one_hr_max            object
doses_per_24_hrs     float64
duration             float64
duration_interval     object
expiration_value     float64
expiration_unit       object
expirationdate        object
dispensation          object
fill_quantity         object
dtype: object

poe - 10,000 rows

In [ ]:
import pandas as pd

# Path to the large CSV file
csv_file_path = '/content/drive/MyDrive/Research/Refeeding/hosp/poe.csv'

# Initialize an empty DataFrame to hold the sample
sample_data = []

# Load the CSV file in chunks
chunk_size = 10000  # Number of rows per chunk
for chunk in pd.read_csv(csv_file_path, chunksize=chunk_size):
    # Append the first 10,000 rows from the first chunk
    sample_data.append(chunk)

    # Stop after collecting enough samples
    if len(sample_data) * chunk_size >= 10000:
        break

# Concatenate the list of DataFrames into a single DataFrame
df_sample = pd.concat(sample_data)[:10000]  # Ensure it contains only 10,000 rows

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/poe_samp.csv', index=False)

# Display data types
print(df_sample.dtypes)

poe_id                    object
poe_seq                    int64
subject_id                 int64
hadm_id                    int64
ordertime                 object
order_type                object
order_subtype             object
transaction_type          object
discontinue_of_poe_id     object
discontinued_by_poe_id    object
order_provider_id         object
order_status              object
dtype: object

poe_detail - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/poe_detail.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/poe_detail_samp.csv', index=False)

df.dtypes

poe_id         object
poe_seq         int64
subject_id      int64
field_name     object
field_value    object
dtype: object

prescriptions - 10,000 rows

In [ ]:
import pandas as pd

# Path to the large CSV file
csv_file_path = '/content/drive/MyDrive/Research/Refeeding/hosp/prescriptions.csv'

# Initialize an empty DataFrame to hold the sample
sample_data = []

# Load the CSV file in chunks
chunk_size = 10000  # Number of rows per chunk
for chunk in pd.read_csv(csv_file_path, chunksize=chunk_size):
    # Append the first 10,000 rows from the first chunk
    sample_data.append(chunk)

    # Stop after collecting enough samples
    if len(sample_data) * chunk_size >= 10000:
        break

# Concatenate the list of DataFrames into a single DataFrame
df_sample = pd.concat(sample_data)[:10000]  # Ensure it contains only 10,000 rows

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/prescriptions_samp.csv', index=False)

# Display data types
print(df_sample.dtypes)

subject_id             int64
hadm_id                int64
pharmacy_id            int64
poe_id                object
poe_seq              float64
order_provider_id     object
starttime             object
stoptime              object
drug_type             object
drug                  object
formulary_drug_cd     object
gsn                   object
ndc                  float64
prod_strength         object
form_rx               object
dose_val_rx           object
dose_unit_rx          object
form_val_disp         object
form_unit_disp        object
doses_per_24_hrs     float64
route                 object
dtype: object

services - 10,000

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/services.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/services_samp.csv', index=False)

df.dtypes

subject_id       int64
hadm_id          int64
transfertime    object
prev_service    object
curr_service    object
dtype: object

transfers - 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/hosp/transfers.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/hosp/transfers_samp.csv', index=False)

df.dtypes

subject_id       int64
hadm_id        float64
transfer_id      int64
eventtype       object
careunit        object
intime          object
outtime         object
dtype: object

##Start the ICU file sample creation

Chart Events Sample 10,000 rows

In [ ]:
import pandas as pd

# Path to the large CSV file
csv_file_path = '/content/drive/MyDrive/Research/Refeeding/icu/chartevents.csv'

# Initialize an empty DataFrame to hold the sample
sample_data = []

# Load the CSV file in chunks
chunk_size = 10000  # Number of rows per chunk
for chunk in pd.read_csv(csv_file_path, chunksize=chunk_size):
    # Append the first 10,000 rows from the first chunk
    sample_data.append(chunk)

    # Stop after collecting enough samples
    if len(sample_data) * chunk_size >= 10000:
        break

# Concatenate the list of DataFrames into a single DataFrame
df_sample = pd.concat(sample_data)[:10000]  # Ensure it contains only 10,000 rows

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/chartevents_samp.csv', index=False)

# Display data types
print(df_sample.dtypes)

subject_id        int64
hadm_id           int64
stay_id           int64
caregiver_id    float64
charttime        object
storetime        object
itemid            int64
value            object
valuenum        float64
valueuom         object
warning         float64
dtype: object

datetimeevents sample 10,000 rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/datetimeevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/datetime_samp.csv', index=False)

df.dtypes

subject_id       int64
hadm_id          int64
stay_id          int64
caregiver_id     int64
charttime       object
storetime       object
itemid           int64
value           object
valueuom        object
warning          int64
dtype: object

icustays - Sample 10,000 Rows

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/icustays.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/icustays_samp.csv', index=False)

df.dtypes

subject_id          int64
hadm_id             int64
stay_id             int64
first_careunit     object
last_careunit      object
intime             object
outtime            object
los               float64
dtype: object

ingredientevents - Sample 10,000

In [2]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/ingredientevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/ingevents_samp.csv', index=False)

df.dtypes

subject_id             int64
hadm_id                int64
stay_id                int64
caregiver_id           int64
starttime             object
endtime               object
storetime             object
itemid                 int64
amount               float64
amountuom             object
rate                 float64
rateuom               object
orderid                int64
linkorderid            int64
statusdescription     object
originalamount         int64
originalrate         float64
dtype: object

inputevents - Sample 10,000

In [3]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/inputevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/inputevents_samp.csv', index=False)

df.dtypes

subject_id                         int64
hadm_id                            int64
stay_id                            int64
caregiver_id                       int64
starttime                         object
endtime                           object
storetime                         object
itemid                             int64
amount                           float64
amountuom                         object
rate                             float64
rateuom                           object
orderid                            int64
linkorderid                        int64
ordercategoryname                 object
secondaryordercategoryname        object
ordercomponenttypedescription     object
ordercategorydescription          object
patientweight                    float64
totalamount                      float64
totalamountuom                    object
isopenbag                          int64
continueinnextdept                 int64
statusdescription                 object
originalamount                   float64
originalrate                     float64
dtype: object

outputevents - Sample 10,000

In [4]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/outputevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/outputevents_samp.csv', index=False)

df.dtypes

subject_id        int64
hadm_id           int64
stay_id           int64
caregiver_id      int64
charttime        object
storetime        object
itemid            int64
value           float64
valueuom         object
dtype: object

procedureevents - 10,000 Sample

In [5]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/Research/Refeeding/icu/procedureevents.csv')

# Take the first 10,000 observations
df_sample = df.head(10000)

# Save to a new CSV file
df_sample.to_csv('/content/drive/MyDrive/Research/Refeeding/icu/procevents_samp.csv', index=False)

df.dtypes

subject_id                    int64
hadm_id                       int64
stay_id                       int64
caregiver_id                float64
starttime                    object
endtime                      object
storetime                    object
itemid                        int64
value                       float64
valueuom                     object
location                     object
locationcategory             object
orderid                       int64
linkorderid                   int64
ordercategoryname            object
ordercategorydescription     object
patientweight               float64
isopenbag                     int64
continueinnextdept            int64
statusdescription            object
originalamount              float64
originalrate                  int64
dtype: object